//User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';

//UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const NO_MORE_DATA = 'NO_MORE_DATA';
export const LOADING_SEARCH_SUGGESTION_DATA = 'LOADING_SEARCH_SUGGESTION_DATA';
export const LOADING_SEARCH_RESULT_DATA = 'LOADING_SEARCH_RESULT_DATA';

//Data reducer types
export const SET_POSTS = 'SET_POSTS';
export const SET_POST = 'SET_POST';
export const LIKE_POST = 'LIKE_POST';
export const UNLIKE_POST = 'UNLIKE_POST';
export const DELETE_POST = 'DELETE_POST';
export const CREATE_POST = 'CREATE_POST';
export const SET_USER_SEARCH_SUGGESTIONS = 'SET_USER_SEARCH_SUGGESTIONS';
export const CLEAR_USER_SEARCH_SUGGESTIONS = 'CLEAR_USER_SEARCH_SUGGESTIONS';
export const SET_USER_SEARCH_RESULTS = 'SET_USER_SEARCH_RESULTS';
export const LOADING_COMMENT_SECTION_DATA = 'LOADING_COMMENT_SECTION_DATA';
export const SET_COMMENT_SECTION_DATA = 'SET_COMMENT_SECTION_DATA';
export const ADD_NEW_POST_COMMENT = 'ADD_NEW_POST_COMMENT';

//Menu reducer types
export const OPEN_MENU = 'OPEN_MENU';
export const CLOSE_MENU = 'CLOSE_MENU';